"""empty message

Revision ID: 32e5dafcd3db
Revises: 
Create Date: 2018-11-07 21:49:42.225374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e5dafcd3db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Phone', sa.VARCHAR(length=12), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('first', sa.VARCHAR(length=128), nullable=True),
    sa.Column('last', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_Phone'), 'customer', ['Phone'], unique=False)
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_index(op.f('ix_customer_first'), 'customer', ['first'], unique=False)
    op.create_index(op.f('ix_customer_last'), 'customer', ['last'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('make', sa.VARCHAR(length=128), nullable=True),
    sa.Column('model', sa.VARCHAR(length=128), nullable=True),
    sa.Column('trim', sa.VARCHAR(length=128), nullable=True),
    sa.Column('color', sa.VARCHAR(length=128), nullable=True),
    sa.Column('plate_state', sa.VARCHAR(length=2), nullable=True),
    sa.Column('plate_number', sa.VARCHAR(length=12), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('workplace', sa.VARCHAR(length=128), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('checkin_token', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_customer_last'), table_name='customer')
    op.drop_index(op.f('ix_customer_first'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_Phone'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
