"""init migration

Revision ID: 751d752ad476
Revises: 
Create Date: 2018-11-06 18:43:05.332739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751d752ad476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Phone', sa.VARCHAR(length=12), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('first', sa.VARCHAR(length=128), nullable=True),
    sa.Column('last', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_Phone'), 'customer', ['Phone'], unique=False)
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_index(op.f('ix_customer_first'), 'customer', ['first'], unique=False)
    op.create_index(op.f('ix_customer_last'), 'customer', ['last'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Year', sa.SmallInteger(), nullable=True),
    sa.Column('Make', sa.VARCHAR(length=128), nullable=True),
    sa.Column('Model', sa.VARCHAR(length=128), nullable=True),
    sa.Column('Trim', sa.VARCHAR(length=128), nullable=True),
    sa.Column('Color', sa.VARCHAR(length=128), nullable=True),
    sa.Column('State', sa.VARCHAR(length=2), nullable=True),
    sa.Column('License Plate', sa.VARCHAR(length=12), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DATE(), nullable=True),
    sa.Column('Type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('Workplace', sa.VARCHAR(length=128), nullable=True),
    sa.Column('Checked In Status', sa.Boolean(), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_customer_last'), table_name='customer')
    op.drop_index(op.f('ix_customer_first'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_Phone'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
